global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.163.com:465'
  smtp_from: 'fmbankops@163.com'
  smtp_auth_username: 'fmbankops@163.com'
  smtp_auth_password: 'Fumin1234'
  smtp_hello: '163.com'
  smtp_require_tls: false
route:
  group_by: ['job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default
  routes:
  - receiver: email
    match:
      alertname: CoreDNSDown
receivers:
- name: 'email'
  email_configs:
  - to: 'dan.bai@aliyun.com'
    send_resolved: true
- name: 'default'
  webhook_configs:
  - url: 'http://dingtalk-hook.kube-ops:5000'
    send_resolved: true
