apiVersion: v1
kind: Service
metadata:
  name: k8s-etcd
  namespace: kube-system
  labels:
    k8s-app: k8s-etcd
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: port
    port: 2379
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: k8s-etcd
  namespace: kube-system
  labels:
    k8s-app: k8s-etcd
subsets:
- addresses:
  - ip: 172.16.0.33
  ports:
  - name: port
    port: 2379
    protocol: TCP
