apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kube-ops
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  clusterIP: None
  ports:
  - name: zk
    port: 2181
  - name: server
    port: 12888
  - name: leader-election
    port: 13888
